name: Updater

on:
  schedule:
    - cron: '0 0 */3 * *' 

permissions:
  contents: write
  pull-requests: write
  
jobs:
  Sync:
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/workflows/actions/setup
        with:
          swift: ${{ matrix.swift }}
          os: ${{ matrix.os }}
      - name: "Sync code base"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          make install
          git push
          # gh pr review --approve "$PR_URL"
          # gh pr merge --auto --merge "$PR_URL"
          
